## ==[ History ]==

set-option -g history-limit 10000

## ==[ Key bindings ]==

# Keys
#set-option -wg mode-keys emacs
#set-option -g status-keys emacs

# ==[ Local config ]==

if-shell "[ -f ~/.tmux-local.conf ]" 'source ~/.tmux-local.conf'
