(setq guide-key/guide-key-sequence '("C-x r" "C-x n" "M-t" "C-c"))
(guide-key-mode 1)
(setq guide-key/recursive-key-sequence-flag t)
(setq guide-key/popup-window-position 'bottom)
;; (setq guide-key/idle-delay 0.1)
